### PR TITLE
89 zksharding page

### PR DESCRIPTION
**Pull request by TowerOneka**
#89

### CODE REVIEW

**Comment by ukorvl** [comment]
This page should be default (instead of proof-market). proof-market is moving to a separate `/proof-market` url.

**Review by KlonD90 — CHANGES_REQUESTED** [review]
это должно стать новой главной а текущая главная должна быть доступна по другому урлу `/proofmarket`

**Comment by ukorvl** [comment]
image
Can we make the distance between text and pattern smaller in mobile representation as on the [template](https://www.figma.com/file/9IKNrBtLd7mkDHnkcVBa1b/Site?type=design&node-id=601-12842&mode=design&t=4GHzHevvuS1yxI7i-0)

**Comment by ukorvl** [comment]
CI failes

**Pull request merged**
